name: Build API

on:
  push:
    branches: [ '**' ]

env:
  APP_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          cache: true
          cache-dependency-path: ./go.sum
          go-version-file: ./go.mod

      - name: Build API
        run: CGO_ENABLED=0 go build -o ./build/server cmd/server.go

      - name: Build docker image
        if: github.ref == 'refs/heads/master'
        run: docker build --tag ${{ env.APP_NAME }} .
